### ISSUE TITLE
coolshell的文章能否做个合集放到这里呢？

### ISSUE THREAD

**Issue by svenyang** [megaease/Remembering-Haoel#25]

**Comment by HeyAlaia** [comment]
希望coolshell可以一直维护下去

**Comment by qdongxu** [comment]
Here's  a repo already: https://github.com/soulteary/forever-coolshell

**Comment by HeyAlaia** [comment]
> Here's a repo already: https://github.com/soulteary/forever-coolshell

thank u，

**Comment by chenshuo** [comment]
静态镜像： https://coolshell.org
源文件： https://github.com/chenshuo/coolshell
