### ISSUE TITLE
需要微博的备份吗?

### ISSUE THREAD

**Issue by Zikinn** [megaease/Remembering-Haoel#60]
如题, 微博也已经备份完了, 需要提交一下微博内容的备份吗?
cc @zhao-kun

**Comment by zhao-kun** [comment]
首先非常感谢。不过微博的内容可能也很多，会导致这个Repository 体积增的太大，给后面添加内容的同学带来一些困扰。 
我想是否可以现在传到Web Archive上， 再以外链的形式进行链接。

再次感谢 @Zikinn 同学了。:pray:

**Comment by Zikinn** [comment]
好像是我太激动了…没确认全都完成就发 issue 了, 又确认了下看到才备份到去年的内容, 是陈老师自己设置了半年可见…
有可能和他的家人沟通下吗, 不过最好过段时间, 等他们心态好一些的时候. 
抱歉.

**Comment by Zikinn** [comment]
如果关掉半年可见, 陈老师的微博总数应该是一万条多一点, 一整天备份完差不多.

**Comment by zhao-kun** [comment]
好的， 这个我们可以和家人沟通， 但是陈皓较早前在微博的言论稍有过激， 我个人担心后面会被人利用做攻击陈皓的手段。 anyway，稍晚后我会和陈皓家人沟通一下， 说清楚利弊， 好让她们进行一个决断。 目前这个Issue， 我暂时就关闭了

**Comment by Zikinn** [comment]
了解, 那我感觉可能还是隐藏掉早期的内容为好, 这俩天已经在小红书和贴吧看到好几条对陈老师说的不太好听的帖子了.

当然,这取决于他家人的意愿; 如果要非公开的备份的话, 或许也可以考虑让陈老师家人使用他的账号, 自己分批导出.

建议使用的项目有两个

- https://github.com/YaoZeyuan/stablog
- https://github.com/meterscao/Speechless

以及需要提醒陈老师家人给他的微博续费 VIP, 因为隐藏半年前的消息的功能只有 VIP 才有, VIP 掉了就全部公开了.

如果有其他需要我帮助的也可以发邮件给我, i@zikin.org .

**Comment by zhao-kun** [comment]
好的
