### ISSUE TITLE
关于陈皓先生的回忆--来自极客时间的《左耳听风》专栏订阅者

### ISSUE THREAD

**Issue by xiaomiwujiecao** [megaease/Remembering-Haoel#71]
2020年4月，我有幸学习了陈皓先生的课程。他的文章不仅值得反复研读，更像是一次心灵的交流和对话。老师的语气亲和温暖，让人感到无比舒适，至今仍在我的脑海里回荡。

作为一个曾经的北漂，我一直怀揣着技术成就的梦想，但当时的漂泊让我感到迷茫。幸好，我遇到了老师，"左耳朵耗子"。老师的专栏让我感到非常的超值，我一有时间就会翻阅。2020年，尤其让我记忆犹新。在口罩时期，做技术的人更加忐忑不安，但是老师的话语却让我的内心更加坚定。

老师的许多课程对我帮助良多，尤其是对待事业、生活以及新技术的态度。我理解到，新技术永远出生于成熟的技术之上，万法归一。我会脚踏实地地学习UNIX和C++，成为一棵参天大树。

我尊敬的老师，您教会了我如何成长，如何坚持，如何在技术的道路上不断前行。我会一直走下去，永远怀念您的教诲。

**Comment by xiaomiwujiecao** [comment]
最后，我希望贡献我之前买的两个域名永久指向即将构建的纪念网站，  `coolshell.xyz`, `coolshell.vip` , 其他的都被买走了，我至今还挂在阿里云的万网上，备注写着： 仅以此域名 remember 左耳朵耗子 -- 陈皓先生，如果有那么一点帮助，请联系我

**Comment by zhao-kun** [comment]
感谢，如果能按[README.md](https://github.com/megaease/Remembering-Haoel#%E7%BA%AA%E5%BF%B5%E5%B7%A6%E8%80%B3%E6%9C%B5%E8%80%97%E5%AD%90)的方式提交PR就更好了。


> 至于域名，多谢好意， 因为coolshell是陈皓的个人博客，我们无权代他接收。

**Comment by xiaomiwujiecao** [comment]
> 感谢，如果能按[README.md](https://github.com/megaease/Remembering-Haoel#%E7%BA%AA%E5%BF%B5%E5%B7%A6%E8%80%B3%E6%9C%B5%E8%80%97%E5%AD%90)的方式提交PR就更好了。
> 
> > 至于域名，多谢好意， 因为coolshell是陈皓的个人博客，我们无权代他接收。

好的，我回头抽空fork一份提交PR

**Comment by zhao-kun** [comment]
好的， 那我暂时先关闭这个issue了。

**Comment by xiaomiwujiecao** [comment]
> 好的， 那我暂时先关闭这个issue了。

好的
